### PR TITLE
Automated dependency upgrades

### PR DESCRIPTION
**Pull request by hc-github-team-secure-vault-ecosystem**
Full log: https://github.com/hashicorp/vault-plugin-database-mongodbatlas/actions/runs/10704959715

  IMPROVEMENTS:
* Updated dependencies:
   * `github.com/hashicorp/go-hclog` v1.6.2 -> v1.6.3
   * `github.com/hashicorp/vault/sdk` v0.11.0 -> v0.13.0
   * `github.com/mongodb-forks/digest` v1.0.5 -> v1.1.0
   * `go.mongodb.org/atlas` v0.36.0 -> v0.37.0
   * `go.mongodb.org/mongo-driver` v1.14.0 -> v1.16.1

### CODE REVIEW

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26223

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26223

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26223

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26223

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26223

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26223

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26223

**Review by Zlaticanin — APPROVED** [review]

**Pull request merged**
